# DataSource Config
server:
  servlet:
    encoding:
      charset: utf-8
      enabled: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/void?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
    username: root
    password: 520czh
  mail:
    default-encoding: UTF-8
    #发送邮件的账户
    username: 136853349@qq.com
    # 授权码（获取方式前文已描述）
    password: rosytfbkfcxlbjid
    # （邮箱服务器地址，获取方式前文已描述）
    # 163 邮箱是smtp.163.com
    # qq邮箱则为smtp.qq.com
    host: smtp.qq.com
    properties:
      mail:
        smtp:
          ssl:
            enable: true
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml

shiro-redis:
  enabled: true
  redis-manager:
    host: 127.0.0.1:6379
markerhub:
  jwt:
    # 加密秘钥
    secret: f4e2e52034348f86b67cde581c0f9eb5
    # token有效时长，7天，单位秒
    expire: 10000
    header: token



